def getBannedWords() -> list[str]:
  return [
              "dogehype",
              "viewers.shop",
              "viewers. shop",
              "viewers .shop",
              "viewers . shop",
              "viewers shop",
              "dghype",
              "add me on",
              "graphic designer",
              "best viewers on",
              "cheap viewers on",
              "streamrise",
              "add me up on",
              "nezhna.com",
              "nezhna. com",
              "nezhna .com",
              "nezhna . com",
              "nezhna com",
              "nezhna",
              "streamviewers.org",
              "streamviewers. org",
              "streamviewers .org",
              "streamviewers . org",
              "streamviewers org",
              "streamviewers",
              "streamboo.com",
              "streamboo .com",
              "streamboo. com",
              "streamboo . com",
              "streamboo com",
              "streamboo",
              "i am a commission artist",
              "cheap V̐iewers",
              "creativefollowers.online",
              "creativefollowers. online",
              "creativefollowers .online",
              "creativefollowers . online",
              "creativefollowers online",
              "creativefollowers",
              "telegram:",
              "adding me up on",
              "best view͙e̤rs",
              "smmtop11.online",
              "smmtop11. online",
              "smmtop11 .online",
              "smmtop11 . online",
              "smmtop11 online",
              "smmtop11",
              "streamboo.live",
              "streamboo .live",
              "streamboo. live",
              "streamboo . live",
              "streamboo live",
              "smmtask.ru",
              "smmtask. ru",
              "smmtask .ru",
              "smmtask . ru",
              "smmtask ru",
              "smmtask",
              "maxexposure.online",
              "maxexposure. online",
              "maxexposure .online",
              "maxexposure . online",
              "maxexposure online",
              "maxexposure",
              "ai viewers"
          ]
